spring.application.name=ai-resume-reviewer
server.port=7090
# Set max file size per file (e.g., 10MB)
spring.servlet.multipart.max-file-size=10MB
# Set max total request size (e.g., 10MB)
spring.servlet.multipart.max-request-size=10MB

spring.ai.openai.api-key=<OPENAI_KEY>
spring.ai.openai.chat.options.model=<GPT_MODEL>
spring.ai.openai.chat.options.temperature=0.2
